cache:
  yarn: true
  directories:
    - node_modules
language: node_js
node_js:
  - "node"
install:
  - "yarn"
script:
  - "yarn build"
after_success:
  - "surge --project ./dist --domain liftlog.surg.sh"