cache:
  yarn: true
  directories:
    - node_modules
language: node_js
node_js:
  - "node"
install:
  - "yarn"
script:
  - "yarn build"
deploy:
  provider: surge
  project: ./dist/
  domain: liftlog.surge.sh
  skip_cleanup: true
